%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: Path to input spreadsheet\Input_spreadsheet.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 22-Feb-2022 14:44:04

opts = spreadsheetImportOptions("NumVariables", 25); %change this depending on number of variables

opts.Sheet = Slide_Info(tissue_section,1);
opts.DataRange = Slide_Info(tissue_section,2);


% Specify column names and types
opts.VariableNames = ["spot", "x", "y", "LE_region", "CTmvp_region", "CTpan_region", "CT_region", "GABRA1", "GABRA2", "GABRA3", "GABRA4", "GABRA5", "GABRA6", "GABRB1", "GABRB2", "GABRB3", "GABRD", "GABRE", "GABRG1", "GABRG2", "GABRG3", "GABRP", "GABRQ", "GABRR1", "GABRR2", "GABRR3"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];


% Specify variable properties
opts = setvaropts(opts, "spot", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "spot", "EmptyFieldRule", "auto");

% Import the data
spot_average_signatures = readtable("Path to input spreadsheet\Input_spreadsheet.xlsx", opts, "UseExcel", false);

clear opts

spot_average_signatures_MASK=spot_average_signatures;
spot_average_signatures_SD_Filtered=spot_average_signatures;
ColumNames=spot_average_signatures.Properties.VariableNames;
Number_signatures=size(spot_average_signatures.Properties.VariableNames,2);

Niche_Index = find(contains(ColumNames,Niche_of_interest))


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%ADD THIS FOR TUMOUR MASKING
%Signatures_Columns='Tumor'; %NEW LINES
%Index= find(contains(ColumNames,'Tumor')) %new LInes
%tumour_mask=spot_average_signatures.(Index)>(mean(spot_average_signatures.(Index))+std(spot_average_signatures.(Index))); %new lines
%clear Signatures_Columns Index %new lines
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%% MASK for the niche

for j=Niche_Index;
niche_locations=spot_average_signatures.(j)>Threshold_niche*(mean(spot_average_signatures.(j))+std(spot_average_signatures.(j)));
end


%% M1 calculation => Amount of the signature that is within the niche

    row=tissue_section;
   

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

for j=4:Number_signatures;
spot_average_signatures_MASK.(j)=spot_average_signatures.(j)>Threshold_Signature*(mean(spot_average_signatures.(j))+std(spot_average_signatures.(j)));
spot_average_signatures_SD_Filtered.(j)=spot_average_signatures.(j).*spot_average_signatures_MASK.(j);

end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%








%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%activate the line below if using tumour masks
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%niche_locations=niche_locations.*tumour_mask;
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

    for k=4:Number_signatures;
    %column=j;
    Filt_Signature_by_Niche_Mask=spot_average_signatures_SD_Filtered.(k).*niche_locations;
    Manders2(row,k-3)=sum(Filt_Signature_by_Niche_Mask)/sum(spot_average_signatures_SD_Filtered.(k));
    Manders_row_names(row,1:2)=([Slide_Info(tissue_section,1) ColumNames(1,Niche_Index)']);
    %%%%% random test

  
    Spot_ID_niche{:,tissue_section}=table2array(spot_average_signatures(niche_locations,1));
   

    for t=1:1 %10000;
    random_niche_locations=niche_locations(randperm(size(niche_locations, 1)),:);
    Filt_Signature_by_Niche_Mask=spot_average_signatures_SD_Filtered.(k).*random_niche_locations;
    random_Manders2(t,1)=sum(Filt_Signature_by_Niche_Mask)/sum(spot_average_signatures_SD_Filtered.(k));
    end


    real_Manders=Manders2(row,k-3);
    Manders2_p_values_overlap(row,k-3)=sum(random_Manders2>real_Manders)/size(random_Manders2,1);
  
    %Asterisks2=string(double(Asterisks)) 
    %newStr = strrep(Asterisks2,"1","*")


    %clear niche_locations 
    end


Manders_column_names=ColumNames(1,4:Number_signatures);




%clear ()
