%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: Path to input spreadsheet\Input_spreadsheet.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 22-Feb-2022 14:44:04



%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

opts.Sheet = Slide_Info(tissue_section,1);
opts.DataRange = Slide_Info(tissue_section,2);


% Specify column names and types
opts.VariableNames = ["spot", "x", "y"];
opts.VariableTypes = ["string", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, "spot", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "spot", "EmptyFieldRule", "auto");

% Import the data
spot_average_signatures = readtable("Path to input spreadsheet\Input_spreadsheet.xlsx", opts, "UseExcel", false);

%% Clear temporary variables
clear opts


count=0;
count_distance=0;



for i=1:size(spot_average_signatures,1)
   
  
       
       
       
        for k=1:size(spot_average_signatures,1)
          count_distance=count_distance+1;
          r_raw_vector(count_distance)=(sqrt((spot_average_signatures.x(k)-spot_average_signatures.x(i))^2+(spot_average_signatures.y(k)-spot_average_signatures.y(i))^2));
             
         
       
         
        end
      
    
 end








%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

